/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Состояние одного прогона агента (запрос юзера → серия действий).
 */
export type AgentRunStatus = "running" | "done" | "failed" | "cancelled";
/**
 * Тип момента, выбранного LLM (объяснимость + цвет чипа в UI).
 */
export type ClipType = "hook" | "emotional_peak" | "complete_thought" | "strong_quote";
/**
 * Откуда исходник: ссылка YouTube или загруженный файл.
 */
export type SourceKind = "youtube" | "upload";
/**
 * Состояние задачи. Им же размечаем `stage` (Phase 0: stage зеркалит status).
 */
export type JobStatus =
  | "queued"
  | "downloading"
  | "transcribing"
  | "selecting"
  | "rendering"
  | "done"
  | "failed"
  | "cancelled";

export interface ClipFlowContract {
  AgentEvent?: AgentEvent;
  AgentRun?: AgentRun;
  AgentRunStatus?: AgentRunStatus;
  CaptionPreset?: CaptionPreset;
  CaptionReply?: CaptionReply;
  CaptionStyle?: CaptionStyle;
  CaptionTrack?: CaptionTrack;
  Chapter?: Chapter;
  ChaptersData?: ChaptersData;
  Clip?: Clip;
  ClipEdit?: ClipEdit;
  ClipOut?: ClipOut;
  ClipType?: ClipType;
  CropOverride?: CropOverride;
  CropWindow?: CropWindow;
  HighlightStyle?: HighlightStyle;
  HookOverlay?: HookOverlay;
  Job?: Job;
  JobStatus?: JobStatus;
  Metrics?: Metrics;
  Segment?: Segment;
  SourceInterval?: SourceInterval;
  SourceKind?: SourceKind;
  TimelineData?: TimelineData;
  TimelineSegment?: TimelineSegment;
  Transcript?: Transcript;
  VideoChapter?: VideoChapter;
  VideoMap?: VideoMap;
  VideoMoment?: VideoMoment;
  Word?: Word;
}
/**
 * Одно событие ленты агент-чата (порядок = хронология).
 *
 * role: user (запрос) | thinking (короткая мысль) | action (применённый тул) |
 * agent (финальный/уточняющий текст) | error (видимый сбой, правило №8).
 * action_* заполняются ТОЛЬКО для role=action (что сделано: было→стало).
 */
export interface AgentEvent {
  action_kind?: string | null;
  after?: string | null;
  before?: string | null;
  role: "user" | "thinking" | "action" | "agent" | "error";
  text: string;
}
/**
 * Прогон агента над ОДНИМ клипом: лента событий + статус. Поллится фронтом.
 */
export interface AgentRun {
  cancellable?: boolean;
  clip_id: string;
  error?: string | null;
  events?: AgentEvent[];
  job_id: string;
  run_id: string;
  status: AgentRunStatus;
}
/**
 * Именованный пресет стиля субтитров (мини brand kit, спека §9).
 */
export interface CaptionPreset {
  highlight?: HighlightStyle | null;
  id: string;
  name: string;
  style: CaptionStyle;
}
/**
 * Караоке-подсветка активного слова. None в треке = караоке выключено.
 */
export interface HighlightStyle {
  animation?:
    | "none"
    | "karaoke_fill"
    | "pop"
    | "bounce"
    | "punch"
    | "fade"
    | "spring"
    | "blur_in"
    | "color_sweep"
    | "drop_in"
    | "glow_pulse"
    | "shake"
    | "slide_up"
    | "flash";
  box?: boolean;
  color?: string;
  scale?: number;
}
/**
 * Стиль субтитров. Компилируется в ASS (рендер) и в CSS (превью) из одной модели.
 */
export interface CaptionStyle {
  alignment?: number;
  box_color?: string | null;
  box_opacity?: number;
  box_radius?: number;
  color?: string;
  emphasis_auto?: boolean;
  emphasis_color?: string | null;
  font?: string;
  margin_v?: number;
  outline_color?: string;
  outline_w?: number;
  shadow?: number;
  size?: number;
  uppercase?: boolean;
}
/**
 * Одна реплика субтитра (чанк 3–5 слов).
 */
export interface CaptionReply {
  emphasis_refs?: number[];
  hidden?: boolean;
  text_override?: string | null;
  word_refs: number[];
}
/**
 * Трек субтитров клипа: стиль + караоке + реплики + опц. топ-текст (хук).
 */
export interface CaptionTrack {
  burn?: boolean;
  highlight?: HighlightStyle | null;
  hook?: HookOverlay | null;
  replies?: CaptionReply[];
  style: CaptionStyle;
}
/**
 * Топ-текст (хук) клипа: цепляющий заголовок СВЕРХУ кадра (T1, наш отличитель —
 * объяснимый хук, привязанный к reason). Рендерится отдельным ASS-событием с верхним
 * якорем (alignment 8) тем же libass-стеком, что субтитры → превью = экспорт, без
 * второго пайплайна. Не пересекается с нижними субтитрами.
 */
export interface HookOverlay {
  animation?: "none" | "pop" | "fade" | "bounce";
  box_color?: string | null;
  box_opacity?: number;
  color?: string;
  duration_sec?: number;
  enabled?: boolean;
  font?: string;
  full_clip?: boolean;
  margin_v?: number;
  outline_color?: string;
  outline_w?: number;
  shadow?: number;
  size?: number;
  text?: string;
  uppercase?: boolean;
}
/**
 * Глава AI-карты видео (источник-время, секунды). Главы покрывают видео непрерывно.
 */
export interface Chapter {
  end: number;
  start: number;
  summary: string;
  title: string;
}
/**
 * Статус+результат генерации AI-карты (кэш data/<job>/chapters.json).
 */
export interface ChaptersData {
  chapters?: Chapter[];
  error?: string | null;
  status: "pending" | "done" | "failed";
}
/**
 * Внутреннее представление готового клипа (пути к артефактам + экономика).
 */
export interface Clip {
  captions_ass_path: string;
  cost_usd: number;
  crop: CropWindow[];
  id: string;
  latency_s: number;
  output_path: string;
  segment: Segment;
}
/**
 * Окно кропа 9:16 в пиксельных координатах source. Phase 0: одно static-окно на клип.
 */
export interface CropWindow {
  h: number;
  t: number;
  w: number;
  x: number;
  y: number;
}
/**
 * Выбранный момент (границы снэпнуты к словам). `reason` — ПОЧЕМУ, 1-2 предложения.
 *
 * `hook`/`why_works` (T1/T2): объяснимость как продукт — цепляющий топ-заголовок и
 * разбор «почему сработает». Опциональны (default None) → старые segments.json валидны.
 */
export interface Segment {
  end: number;
  hook?: string | null;
  hook_style?: string | null;
  reason: string;
  score: number;
  start: number;
  type: ClipType;
  why_works?: string | null;
}
/**
 * РЕЦЕПТ клипа — не-деструктивный edit-state. Версионируется (optimistic-lock).
 */
export interface ClipEdit {
  aspect?: string;
  captions: CaptionTrack;
  id: string;
  reframe_overrides?: CropOverride[];
  source_intervals: SourceInterval[];
  version?: number;
}
/**
 * Ручной кроп на диапазон source — поверх авто-reframe (MVP: применяется per-интервал).
 */
export interface CropOverride {
  center?: number | null;
  center_b?: number | null;
  mode: string;
  source_end: number;
  source_start: number;
}
/**
 * Один оставленный кусок исходника. Интервалы упорядочены по CLIP-порядку.
 */
export interface SourceInterval {
  source_end: number;
  source_start: number;
}
/**
 * Клип в ответе API. `start/end` — в координатах source (фундамент clip↔source).
 *
 * `words[]` присутствует уже в Phase 0 (фундамент trim-редактора), UI его игнорирует.
 */
export interface ClipOut {
  duration: number;
  end: number;
  hook?: string | null;
  hook_style?: string | null;
  id: string;
  reason: string;
  score: number;
  start: number;
  thumbnail_url?: string | null;
  transcript: string;
  type: ClipType;
  video_url: string;
  why_works?: string | null;
  words: Word[];
}
/**
 * Слово с word-level таймингами (фундамент всего: субтитры, trim, маппинг).
 */
export interface Word {
  confidence?: number | null;
  end: number;
  start: number;
  text: string;
}
/**
 * Состояние задачи целиком — ответ `GET /jobs/{id}` (§4.3).
 */
export interface Job {
  cancellable?: boolean;
  clips?: ClipOut[];
  error?: string | null;
  id: string;
  metrics?: Metrics | null;
  progress: number;
  source_kind: SourceKind;
  stage: JobStatus;
  status: JobStatus;
}
/**
 * Экономика/латентность прогона (на виду в UI).
 */
export interface Metrics {
  cost_usd: number;
  duration_sec: number;
  elapsed_sec: number;
}
/**
 * Данные таймлайн-редактора: длительность + ВСЕ кандидаты ИИ + пословный транскрипт.
 *
 * Собирается из готовых segments.json + transcript.json (без новых ИИ-вызовов).
 * `words` — для hover-подсказок «что тут происходит».
 */
export interface TimelineData {
  duration: number;
  segments: TimelineSegment[];
  words: Word[];
}
/**
 * Кандидат-момент ИИ на таймлайне (маркер). `clip_id`=None, если момент не стал клипом.
 */
export interface TimelineSegment {
  clip_id?: string | null;
  end: number;
  reason: string;
  score: number;
  start: number;
  type: ClipType;
}
/**
 * Нормализованный транскрипт. `words` отсортированы по `start`.
 */
export interface Transcript {
  duration: number;
  language: string;
  words: Word[];
}
/**
 * Глава видео с вложенными моментами и ссылками на клипы.
 */
export interface VideoChapter {
  clip_ids?: string[];
  end: number;
  moments?: VideoMoment[];
  start: number;
  summary: string;
  title: string;
}
/**
 * Интересный момент внутри главы (детальная разметка для фронта).
 */
export interface VideoMoment {
  end: number;
  kind: string;
  label: string;
  start: number;
  why: string;
}
/**
 * Статус+результат нарративного анализа видео (кэш data/<job>/video_map.json).
 */
export interface VideoMap {
  chapters?: VideoChapter[];
  error?: string | null;
  narrative?: string;
  status?: "pending" | "done" | "failed";
}
