/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Тип момента, выбранного LLM (объяснимость + цвет чипа в UI).
 */
export type ClipType = "hook" | "emotional_peak" | "complete_thought" | "strong_quote";
/**
 * Откуда исходник: ссылка YouTube или загруженный файл.
 */
export type SourceKind = "youtube" | "upload";
/**
 * Состояние задачи. Им же размечаем `stage` (Phase 0: stage зеркалит status).
 */
export type JobStatus = "queued" | "downloading" | "transcribing" | "selecting" | "rendering" | "done" | "failed";

export interface ClipFlowContract {
  Clip?: Clip;
  ClipOut?: ClipOut;
  ClipType?: ClipType;
  CropWindow?: CropWindow;
  Job?: Job;
  JobStatus?: JobStatus;
  Metrics?: Metrics;
  Segment?: Segment;
  SourceKind?: SourceKind;
  Transcript?: Transcript;
  Word?: Word;
}
/**
 * Внутреннее представление готового клипа (пути к артефактам + экономика).
 */
export interface Clip {
  captions_ass_path: string;
  cost_usd: number;
  crop: CropWindow[];
  id: string;
  latency_s: number;
  output_path: string;
  segment: Segment;
}
/**
 * Окно кропа 9:16 в пиксельных координатах source. Phase 0: одно static-окно на клип.
 */
export interface CropWindow {
  h: number;
  t: number;
  w: number;
  x: number;
  y: number;
}
/**
 * Выбранный момент (границы снэпнуты к словам). `reason` — ПОЧЕМУ, 1-2 предложения.
 */
export interface Segment {
  end: number;
  reason: string;
  score: number;
  start: number;
  type: ClipType;
}
/**
 * Клип в ответе API. `start/end` — в координатах source (фундамент clip↔source).
 *
 * `words[]` присутствует уже в Phase 0 (фундамент trim-редактора), UI его игнорирует.
 */
export interface ClipOut {
  duration: number;
  end: number;
  id: string;
  reason: string;
  score: number;
  start: number;
  thumbnail_url?: string | null;
  transcript: string;
  type: ClipType;
  video_url: string;
  words: Word[];
}
/**
 * Слово с word-level таймингами (фундамент всего: субтитры, trim, маппинг).
 */
export interface Word {
  confidence?: number | null;
  end: number;
  start: number;
  text: string;
}
/**
 * Состояние задачи целиком — ответ `GET /jobs/{id}` (§4.3).
 */
export interface Job {
  clips?: ClipOut[];
  error?: string | null;
  id: string;
  metrics?: Metrics | null;
  progress: number;
  source_kind: SourceKind;
  stage: JobStatus;
  status: JobStatus;
}
/**
 * Экономика/латентность прогона (на виду в UI).
 */
export interface Metrics {
  cost_usd: number;
  duration_sec: number;
  elapsed_sec: number;
}
/**
 * Нормализованный транскрипт. `words` отсортированы по `start`.
 */
export interface Transcript {
  duration: number;
  language: string;
  words: Word[];
}
